import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import './app.scss';
import Header from "./components/Header";
import 'swiper/css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "./components/Footer";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${poppins.variable}`}>
      <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
